const path = Bun.env.PATH;
const home = Bun.env.HOME;
if (!path) throw new Error("❌ PATH is not set");
if (!home) throw new Error("❌ HOME is not set");
const splittedPath = path.split(":");
splittedPath.push(`${home}/.pulumi/bin`);
splittedPath.push(`${home}/.deno/bin`);
splittedPath.push(`${home}/.bun/bin`);
splittedPath.push(`${home}/go/bin`);
splittedPath.push(`${home}/.arkade/bin`);
splittedPath.push(`${home}/.krew/bin`);
splittedPath.push(`${home}/.cargo/bin`);
splittedPath.push(`${home}/.dotnet`);
splittedPath.push(`${home}/.dotnet/tools`);
splittedPath.push(`${home}/.go/bin`);
splittedPath.push(`${home}/.local/bin`);
splittedPath.push(`${home}/bin`);
splittedPath.push(`${home}/snap/bin`);
splittedPath.push(`${home}/usr/local/sbin`);
splittedPath.push(`${home}/usr/sbin`);
splittedPath.push(`${home}/sbin`);
Bun.env.PATH = splittedPath.join(":");
